

typedef enum{
    COLOR_INVALID=-1,
    COLOR_BLACK,
    COLOR_RED,
    COLOR_GREEN,
    COLOR_YELLOW,
    COLOR_BLUE,
    COLOR_PURPLE,
    COLOR_CYAN,
    COLOR_WHITE,
    COLOR_END,
}color_t;

typedef enum{
    STYLE_INVALID=-1,
    STYLE_DISABLED,
    STYLE_BOLD,
    STYLE_GREY,
    STYLE_ITALIC,
    STYLE_UNDERSCORE,
    STYLE_BLINK,
    STYLE_UNUSED,
    STYLE_REVERSE,
    STYLE_CONCEALED,
    STYLE_END,
}style_t;


#define GRAPH_PAR (FOR,BACK,STY) 